//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedRoomTb
    {
        public int ID { get; set; }
        public int ID_user { get; set; }
        public int ID_room { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual UserTb UserTb { get; set; }
        public virtual RoomTb RoomTb { get; set; }
    }
}
